name: Django-ORM-Mastery

services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  django:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "
        uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --reload
      "